"""ngspice validation of the KLM-76 ensemble netlist against hand theory:
input-chain and reconstruction-ladder transfer functions, mixer gain
structure, comb-notch positions of the behavioral BBD delay, the CD4069
three-phase LFO rates/phases, and the clock-astable VCO law.

The SPICE-fitted constants used by dsp/ensemble.dsp are re-derived here from
the netlist on every run (DSP_CONST below mirrors the .dsp file; keep in
sync)."""

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pytest

REPO = Path(__file__).resolve().parent.parent
NETLIST = REPO / "netlists" / "klm76-ensemble.cir"

pytestmark = pytest.mark.skipif(shutil.which("ngspice") is None, reason="ngspice not installed")

# --- constants mirrored in dsp/ensemble.dsp (keep in sync) ---------------
# each is re-derived from the netlist by a test below.
# Per the full-res scan re-read (U6), the LFO output is wired DC-direct to
# the astable FM node: Vfm = vmid + a_lfo*sin (CD4069 on 0/+14.9 V rails),
# no divider, no coupling cap.
DSP_CONST = {
    "f0v": 37209.9,  # clock astable law intercept [Hz] at Vfm = 0 (linear fit)
    "kv": 1868.74,  # clock FM slope [Hz/V]
    "nbbd": 256.0,  # MN3004: 512 stages -> tau = 256/fclk
    "lfo_fa": 3.0599,  # LFO A rate [Hz] (C = 0.039u)
    "lfo_fb": 2.5391,  # LFO B rate [Hz] (C = 0.047u)
    "a_lfo": 7.20,  # ring output amplitude [Vpk] (rail-clipped)
    "vmid": 7.45,  # ring output midpoint [V] (CD4069 on 0/+14.9 V)
    "kfol": 0.96839,  # 2SA733 follower insertion gain (flat fit)
    "lad_poles": (3841.686, 28570.334, 148195.370),  # ladder poles [Hz]
}


def tau_of(phase: float) -> float:
    """BBD delay [s] for a frozen LFO phase (turns), same law as the DSP."""
    vfm = DSP_CONST["vmid"] + DSP_CONST["a_lfo"] * np.sin(2 * np.pi * phase)
    return DSP_CONST["nbbd"] / (DSP_CONST["f0v"] + DSP_CONST["kv"] * vfm)


# --- ngspice drivers ------------------------------------------------------


def run_audio_ac(
    td1: float, td2: float, g1: float = 1.0, g2: float = 1.0, npts: int = 3000
) -> dict[str, np.ndarray]:
    """AC sweep of the audio path; returns dB traces (see netlist wrdata)."""
    deck = NETLIST.read_text()
    deck = re.sub(
        r"^\.param .*$",
        f".param TD1={td1} TD2={td2} G1={g1} G2={g2}",
        deck,
        count=1,
        flags=re.MULTILINE,
    )
    deck = re.sub(r"^ac lin .*$", f"ac lin {npts} 20 12020", deck, count=1, flags=re.MULTILINE)
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        (tmpdir / "deck.cir").write_text(deck)
        proc = subprocess.run(
            ["ngspice", "-b", "deck.cir"], cwd=tmpdir, capture_output=True, text=True
        )
        out = tmpdir / "ens_ac.txt"
        if not out.exists():
            raise RuntimeError(f"ngspice produced no output:\n{proc.stdout}\n{proc.stderr}")
        data = np.loadtxt(out)
    names = ["out", "pre", "bbd1in", "bbd1o", "e405"]
    res = {"freq": data[:, 0]}
    for i, n in enumerate(names):
        res[n] = data[:, 2 * i + 1]
    return res


def netlist_blocks(*subckts: str) -> str:
    """Extract .model lines and named .subckt blocks from the netlist, so
    measurement decks share the single transcription."""
    text = NETLIST.read_text()
    parts = [ln for ln in text.splitlines() if ln.startswith(".model ")]
    for name in subckts:
        m = re.search(rf"(?ms)^\.subckt {name}\b.*?^\.ends", text)
        assert m, f"subckt {name} not found in {NETLIST}"
        parts.append(m.group(0))
    return "\n".join(parts)


def run_deck(deck: str, outfile: str) -> np.ndarray:
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        (tmpdir / "deck.cir").write_text(deck)
        proc = subprocess.run(
            ["ngspice", "-b", "deck.cir"], cwd=tmpdir, capture_output=True, text=True
        )
        out = tmpdir / outfile
        if not out.exists():
            raise RuntimeError(f"ngspice produced no output:\n{proc.stdout}\n{proc.stderr}")
        return np.loadtxt(out)


def rising_crossings(t: np.ndarray, v: np.ndarray, level: float) -> np.ndarray:
    vv = v - level
    idx = np.where((vv[:-1] < 0) & (vv[1:] >= 0))[0]
    return t[idx] + (t[idx + 1] - t[idx]) * (-vv[idx]) / (vv[idx + 1] - vv[idx])


@pytest.fixture(scope="module")
def lfo_runs() -> dict[float, np.ndarray]:
    """Transient of both ring LFOs (lfo3 subckt from the netlist)."""
    runs = {}
    for c in (0.039e-6, 0.047e-6):
        deck = f"""* LFO measurement deck (generated by test_ensemble_spice)
{netlist_blocks("inv4069", "lfo3")}
XL a1 a2 a3 lfo3 C={c}
.ic v(xl.n1)=2.0
.control
tran 1m 14s 0 1m
wrdata lfo_out.txt v(a1) v(a2) v(a3)
.endc
.end
"""
        runs[c] = run_deck(deck, "lfo_out.txt")
    return runs


def vco_frequency(vfm: float) -> float:
    """Clock astable frequency at a DC FM voltage (clkvco subckt).
    reltol is tightened: at the default 1e-3 the astable period carries ~10%
    solver jitter; at 1e-4 it is periodic to < 0.01%."""
    deck = f"""* VCO law measurement deck (generated by test_ensemble_spice)
{netlist_blocks("clkvco")}
.options reltol=1e-4 abstol=1e-12
VNN vnn 0 -14.9
VF fm 0 {vfm}
XV fm cp1 cp2 vnn clkvco
.ic v(xv.b1)=-16 v(xv.b2)=-14.2
.control
tran 0.02u 3m 2m 0.05u
wrdata vco_out.txt v(xv.c1)
.endc
.end
"""
    d = run_deck(deck, "vco_out.txt")
    t, v = d[:, 0], d[:, 1]
    c = rising_crossings(t, v, (v.max() + v.min()) / 2)
    return 1.0 / np.diff(c).mean()


# --- analytic references --------------------------------------------------


def input_chain_theory(f: np.ndarray) -> np.ndarray:
    """|H| in dB, pin 43 -> BBD input (divider+C401, IC-44a shelf, R406/C404
    pole, C410/R411/R412 coupling HPF). Values from the netlist."""
    s = 2j * np.pi * f
    r401, r402, r403, c401 = 47e3, 47e3, 1e3, 470e-12
    r404, r405, c402, c403 = 2.2e3, 22e3, 100e-12, 1000e-12
    r406, c404 = 22e3, 470e-12
    c410, r411, r412 = 1e-6, 220.0, 100e3
    hdiv = 0.5 / (1 + s * c401 * (r401 * r402 / (r401 + r402) + r403))
    num = 1 + s * (r404 * c403 + r405 * c402 + r405 * c403) + s**2 * r404 * r405 * c403 * c402
    den = (1 + s * r404 * c403) * (1 + s * r405 * c402)
    h2 = 1 / (1 + s * r406 * c404)
    hhp = s * c410 * r412 / (1 + s * c410 * (r411 + r412))
    return 20 * np.log10(np.abs(hdiv * num / den * h2 * hhp))


def ladder_poly() -> tuple[float, float, float]:
    """1 + a1 s + a2 s^2 + a3 s^3 of the reconstruction ladder (standard RC
    ladder polynomial; R1 = R422||R423 sees both BBD output pins)."""
    r1, c1 = 1.1e3, 1000e-12
    r2, c2 = 47e3, 680e-12
    r3, c3 = 47e3, 150e-12
    a1 = r1 * c1 + (r1 + r2) * c2 + (r1 + r2 + r3) * c3
    a2 = r1 * c1 * (r2 * c2 + (r2 + r3) * c3) + (r1 + r2) * c2 * r3 * c3
    a3 = r1 * c1 * r2 * c2 * r3 * c3
    return a1, a2, a3


def ladder_theory(f: np.ndarray) -> np.ndarray:
    a1, a2, a3 = ladder_poly()
    s = 2j * np.pi * f
    return 20 * np.log10(np.abs(1 / (1 + a1 * s + a2 * s**2 + a3 * s**3)))


# --- audio-path tests -----------------------------------------------------


def test_input_chain_matches_theory():
    res = run_audio_ac(5.004e-3, 5.004e-3)
    err = np.abs(input_chain_theory(res["freq"]) - res["bbd1in"])
    assert err.max() < 0.05, f"input chain vs theory: {err.max():.3f} dB"


def test_ladder_matches_theory_and_follower_fit():
    """The passive ladder matches the exact RC-ladder polynomial once the
    2SA733 follower's flat insertion loss is factored out; the fitted gain is
    the kfol constant used by the DSP."""
    res = run_audio_ac(5.004e-3, 5.004e-3)
    err_db = ladder_theory(res["freq"]) - (res["e405"] - res["bbd1o"])
    kfol = 10 ** (-err_db.mean() / 20)
    assert kfol == pytest.approx(DSP_CONST["kfol"], abs=0.005)
    # residual after removing the flat fit: base loading is nearly constant
    # over the band (< 0.1 dB shape)
    assert np.ptp(err_db) < 0.15


def test_ladder_poles_documented():
    a1, a2, a3 = ladder_poly()
    roots = np.roots([a3, a2, a1, 1.0])
    assert np.abs(roots.imag).max() == 0.0  # RC ladder: all poles real
    poles = np.sort(-roots.real) / (2 * np.pi)
    for got, doc in zip(poles, DSP_CONST["lad_poles"]):
        assert got == pytest.approx(doc, rel=1e-3)


def test_mixer_dry_leg():
    """Both BBD channels muted: out = -R466/R465 * dry, flat.
    (Mute = 1e-6, not 0: vdb() of an exactly-zero node aborts ngspice.)"""
    res = run_audio_ac(5.004e-3, 5.004e-3, g1=1e-6, g2=1e-6)
    dry_db = 20 * np.log10(100e3 / 180e3)
    err = np.abs(res["out"] - dry_db)
    assert err.max() < 0.05, f"dry leg: {err.max():.3f} dB from {dry_db:.2f} dB"


def test_comb_notch_positions_follow_delay():
    """Single wet channel + dry: notches near (k+1/2)/tau. The wet arm's
    filter group delay (~40 us: ladder + input chain at 1 kHz) adds ~0.6% to
    the effective delay, so allow 1.5%; notch SPACING isolates tau itself and
    is held to 1%."""
    tau = tau_of(0.75)
    res = run_audio_ac(tau, tau, g1=1.0, g2=1e-6, npts=12000)
    f, db = res["freq"], res["out"]
    m = (f >= 500) & (f <= 3000)
    fm, dm = f[m], db[m]
    idx = np.where((dm[1:-1] < dm[:-2]) & (dm[1:-1] < dm[2:]))[0] + 1
    notches = np.array([fm[i] for i in idx if dm[i] < np.median(dm) - 6])
    assert len(notches) >= 10
    k = np.round(notches * tau - 0.5)
    ideal = (k + 0.5) / tau
    assert np.abs(notches / ideal - 1).max() < 0.015
    spacing = np.diff(notches).mean()
    assert spacing == pytest.approx(1.0 / tau, rel=0.01)


# --- LFO tests ------------------------------------------------------------


def lfo_metrics(d: np.ndarray) -> dict[str, float]:
    t = d[:, 0]
    m = t > 8.0  # discard startup growth
    tm = t[m]
    v1, v2, v3 = d[m, 1], d[m, 3], d[m, 5]
    c1 = rising_crossings(tm, v1, v1.mean())
    per = np.diff(c1).mean()
    out = {"f": 1.0 / per, "amp": (v1.max() - v1.min()) / 2, "mid": (v1.max() + v1.min()) / 2}
    for name, v in (("lag2", v2), ("lag3", v3)):
        c = rising_crossings(tm, v, v.mean())
        dt = c - c1[0]
        dt = dt[(dt >= 0) & (dt < per)]
        out[name] = dt[0] / per * 360.0
    return out


def test_lfo_a_rate_amplitude_phases(lfo_runs):
    m = lfo_metrics(lfo_runs[0.039e-6])
    # linear phase-shift theory: f = sqrt(3)/(2 pi Rf C) = 2.14 Hz; the ring
    # has excess gain 3.3*cos(60) = 1.65, so it rail-clips and runs faster
    # (relaxation-like) -- bound the ratio, pin the measured value
    f_lin = np.sqrt(3) / (2 * np.pi * 3.3e6 * 0.039e-6)
    assert 1.2 < m["f"] / f_lin < 1.7
    assert m["f"] == pytest.approx(DSP_CONST["lfo_fa"], rel=0.02)
    assert m["amp"] == pytest.approx(DSP_CONST["a_lfo"], abs=0.15)
    # DC level of the ring output = the astable's static FM level (the
    # coupling is DC-direct per the re-read, U6)
    assert m["mid"] == pytest.approx(DSP_CONST["vmid"], abs=0.2)
    # three-phase: stages lag 120 deg each around the ring
    assert m["lag2"] == pytest.approx(240.0, abs=12.0)
    assert m["lag3"] == pytest.approx(120.0, abs=12.0)


def test_lfo_b_rate_tracks_cap_ratio(lfo_runs):
    ma_ = lfo_metrics(lfo_runs[0.039e-6])
    mb = lfo_metrics(lfo_runs[0.047e-6])
    assert mb["f"] == pytest.approx(DSP_CONST["lfo_fb"], rel=0.02)
    # same topology, only C changes: rates scale as C_A/C_B
    assert ma_["f"] / mb["f"] == pytest.approx(0.047 / 0.039, rel=0.02)


# --- clock VCO tests ------------------------------------------------------


@pytest.fixture(scope="module")
def vco_law() -> tuple[np.ndarray, np.ndarray]:
    # the FM node is DC-wired to the ring output (U6 re-read): sweep its
    # actual range, vmid +/- a_lfo
    vs = DSP_CONST["vmid"] + DSP_CONST["a_lfo"] * np.array([-1.0, -0.5, 0.0, 0.5, 1.0])
    fs = np.array([vco_frequency(v) for v in vs])
    return vs, fs


def test_vco_free_run_matches_hand_theory(vco_law):
    """Classic cross-coupled astable with base recovery through RB 130k to
    the FM level: half period RB*C*ln((Vfm+Vth+dV)/(Vfm+Vth)) with C 150p,
    Vth = 14.9 - Vd(D404/5) - Vbe ~ 13.65 (emitters ride one diode above
    -14.9), collector swing dV ~ 14.2. At the ring midpoint +7.45 V this
    gives ~50 kHz. Generic BJT models justify 15%."""
    vs, fs = vco_law
    f0 = fs[2]  # Vfm = vmid
    rb, c, dv, vth = 130e3, 150e-12, 14.2, 13.65
    vmid = DSP_CONST["vmid"]
    t_half = rb * c * np.log((vmid + vth + dv) / (vmid + vth))
    assert f0 == pytest.approx(1.0 / (2 * t_half), rel=0.15)
    # MN3004 wants 10..100 kHz; the resulting delay is ensemble territory
    assert 10e3 < f0 < 100e3
    assert 3e-3 < DSP_CONST["nbbd"] / f0 < 8e-3
    # the whole modulated range must stay inside the MN3004 clock rating
    assert 10e3 < fs.min() and fs.max() < 100e3


def test_vco_law_linear_and_documented(vco_law):
    vs, fs = vco_law
    kv, f0v = np.polyfit(vs, fs, 1)
    resid = np.abs(np.polyval([kv, f0v], vs) - fs).max()
    assert resid < 100.0, "clock law deviates from linear fit"
    assert f0v == pytest.approx(DSP_CONST["f0v"], rel=0.02)
    assert kv == pytest.approx(DSP_CONST["kv"], rel=0.05)
    assert np.all(np.diff(fs) > 0), "clock frequency must rise with Vfm"
