"""ngspice validation of the KLM-76 sample & hold (netlists/klm76-sh.cir)
against hand theory: the traced transistor clock's exponential rate law and
1.2 Hz center calibration (VR1), the no-stall minimum rate, external sync
capture through C5, sample acquisition accuracy through the JFET switch and
the 1.1x input buffer, and the hold droop rate set by the bias current on
the hold cap. Transient decks are generated by regex-substituting the
.param, Vin, Rsync, and tran lines of the reference netlist (the
analysis/ac_analysis.py pattern)."""

import math
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pytest

REPO = Path(__file__).resolve().parent.parent
NETLIST = REPO / "netlists" / "klm76-sh.cir"

pytestmark = pytest.mark.skipif(shutil.which("ngspice") is None, reason="ngspice not installed")

# constants mirroring the netlist (and dsp/sh.dsp)
# Traced clock law: the Q3/Q4 exponential
# converter gives f = F0_CENTER * exp(K_PER_VOLT * (vpot - 5)).
# F0_CENTER is the VR1 calibration target (panel "~1.2 Hz AT CENTER
# POSITION"); K_PER_VOLT is fitted to a SPICE sweep of the transistor
# netlist (residual < 1.5% over vpot 0..10) and matches the hand theory
# d ln f / dVpot = (R12 || R9 || R11)/R9 / VT ~ 0.56/V.
F0_CENTER = 1.2
K_PER_VOLT = 0.5588
C6 = 0.1e-6
C9 = 0.1e-6  # hold capacitor
T_PULSE = 1.33e-3  # sample pulse width: C7*(R13||R14)*ln(dV/1.354V), SPICE-measured
GAIN_BUF = 1.1  # IC1b: 1 + R17/R16
TRACES = ["out", "ct", "clk", "hold", "bout"]


def clock_freq_theory(vpot: float) -> float:
    """Exponential-converter law fitted to the transistor-level netlist."""
    return F0_CENTER * math.exp(K_PER_VOLT * (vpot - 5.0))


def clock_period_theory(vpot: float) -> float:
    return 1.0 / clock_freq_theory(vpot)


def run_tran(
    vpot: float = 5.0,
    tstop: float = 5.0,
    tstep: float = 5e-4,
    ibias: float = 10e-12,
    vindc: float = 2.0,
    vin_line: str | None = None,
    sync_line: str | None = None,
    ngspice: str = "ngspice",
) -> dict[str, np.ndarray]:
    """One transient run; returns {'t', 'out', 'ct', 'clk', 'hold', 'bout'}."""
    deck = NETLIST.read_text()
    deck = re.sub(
        r"^\.param vpot=.*$",
        f".param vpot={vpot} ibias={ibias} vindc={vindc}",
        deck,
        count=1,
        flags=re.MULTILINE,
    )
    # cap the internal timestep at 100 us: the latch fires on us-scale kicks
    # (sync edges through C5) that solvers otherwise resolve differently -
    # ngspice 42 (CI) vs 46 diverge on capture without this
    deck = re.sub(r"^tran .*$", f"tran {tstep} {tstop} 0 1e-4", deck, count=1, flags=re.MULTILINE)
    if vin_line is not None:
        deck = re.sub(r"^Vin .*$", vin_line, deck, count=1, flags=re.MULTILINE)
    if sync_line is not None:
        deck = re.sub(r"^Rsync .*$", sync_line, deck, count=1, flags=re.MULTILINE)
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        (tmpdir / "deck.cir").write_text(deck)
        proc = subprocess.run(
            [ngspice, "-b", "deck.cir"], cwd=tmpdir, capture_output=True, text=True
        )
        out_file = tmpdir / "sh_out.txt"
        if not out_file.exists():
            raise RuntimeError(f"ngspice produced no output:\n{proc.stdout}\n{proc.stderr}")
        data = np.loadtxt(out_file)
    result = {"t": data[:, 0]}
    for i, name in enumerate(TRACES):
        result[name] = data[:, 2 * i + 1]
    return result


def clock_edges(res: dict[str, np.ndarray]) -> np.ndarray:
    """Rising-edge times of the internal clock pulse."""
    hi = res["clk"] > 2.5
    return res["t"][1:][(~hi[:-1]) & hi[1:]]


@pytest.fixture(scope="module")
def center_run() -> dict[str, np.ndarray]:
    """Pot at center (5 V wiper), 2 V DC input: 3 clock edges in 2.6 s."""
    return run_tran(vpot=5.0, tstop=2.6, vindc=2.0)


@pytest.mark.parametrize("vpot", [4.0, 7.0, 10.0])
def test_clock_rate_follows_expo_law(vpot):
    """Measured rate tracks the exponential-converter law
    f = 1.2 * exp(0.5588*(vpot-5)) over the pot travel. Tolerance 3%: the
    single (F0, K) pair fitted over the whole 0..10 V sweep leaves <1.5%
    residual (slight top-end compression from Q3's base-current loading of
    the R5 bias); doubled for measurement headroom."""
    T = clock_period_theory(vpot)
    res = run_tran(vpot=vpot, tstop=4.5 * T + 0.5, tstep=min(5e-4, T / 50))
    periods = np.diff(clock_edges(res))
    assert len(periods) >= 2
    assert periods.mean() == pytest.approx(T, rel=0.03)


def test_center_position_is_1p2_hz(center_run):
    """Panel annotation '~1.2 Hz AT CENTER POSITION' (smudged read, see scan
    doc): VR1 (FREQ.ADJ) is calibrated to it, so SPICE must reproduce it."""
    periods = np.diff(clock_edges(center_run))
    assert 1.0 / periods.mean() == pytest.approx(1.2, rel=0.05)


def test_min_rate_no_stall():
    """Pot fully CCW (vpot=0): the exponential current sink never reaches
    zero, so the traced clock does NOT stall - it runs at the law's minimum
    (~0.072 Hz). This replaces the old functional model's spurious stall
    below pot ~0.3."""
    T = clock_period_theory(0.0)  # ~13.8 s
    res = run_tran(vpot=0.0, tstop=3.2 * T, tstep=2e-3)
    periods = np.diff(clock_edges(res))
    assert len(periods) >= 2
    assert periods.mean() == pytest.approx(T, rel=0.03)


def test_sync_capture():
    """External sync: 1.5 Hz positive pulses into SYNC IN (pin 8, C5 into the
    R6/R8 divider node) capture the 1.2 Hz free-running clock 1:1 - each
    external rising edge lifts node B through R7/D1 and fires the latch
    early. 1.5 Hz leaves a real capture margin (the ramp has descended ~80%
    of the way when the kick arrives); 2 Hz sits at the edge of the 1:1
    range where capture is decided by solver integration detail (ngspice 42
    vs 46 disagree), and 3 Hz is outside it - expected of a relaxation
    oscillator."""
    res = run_tran(
        vpot=5.0,
        tstop=3.0,
        sync_line="Vsync syncin 0 PULSE(0 10 0.05 1u 1u 5m 0.66667)",
    )
    periods = np.diff(clock_edges(res))
    assert len(periods) >= 3
    assert np.all(np.abs(periods - 0.66667) < 0.01)


def test_buffer_gain(center_run):
    """IC1b non-inverting buffer: 1 + R17/R16 = 1.1x on the S/H input."""
    t, bout = center_run["t"], center_run["bout"]
    assert bout[t > 1.0].mean() == pytest.approx(GAIN_BUF * 2.0, rel=0.01)


def test_acquisition_accuracy(center_run):
    """One ~1.33 ms pulse (>> the 18.5 us JFET-Ron*C9 time constant)
    acquires the buffered input to well under 1%; before the first pulse the
    hold cap still sits at 0."""
    t = center_run["t"]
    first_edge = clock_edges(center_run)[0]
    # before the first pulse nothing is sampled: the output sits at the DC
    # operating point (a ~24 mV artifact of the off-JFET gmin network; the
    # real cap powers up at an arbitrary level) and must not move
    pre = center_run["out"][t < first_edge - 0.01]
    assert np.all(np.abs(pre) < 0.05)
    assert pre.max() - pre.min() < 5e-3
    held = center_run["hold"][(t > first_edge + 0.05) & (t < first_edge + 0.5)]
    assert held.mean() == pytest.approx(GAIN_BUF * 2.0, rel=1e-3)
    # buffered output only differs by the R25/Rload test divider (0.05%)
    out = center_run["out"][(t > first_edge + 0.05) & (t < first_edge + 0.5)]
    assert out.mean() == pytest.approx(GAIN_BUF * 2.0, rel=2e-3)


def test_droop_rate_is_ibias_over_c9():
    """Hold-mode droop slope = -Ibias/C9. Ibias is cranked to 100 nA (1 V/s)
    so the slope dominates the ~17 pA ngspice GMIN leakage floor (at the real CA3140's 10 pA the physical droop
    is ~0.1 mV/s)."""
    ibias = 100e-9
    res = run_tran(vpot=5.0, tstop=1.6, ibias=ibias, vindc=2.0)
    edges = clock_edges(res)
    # hold interval inside the first (~0.9 s) to second (~1.73 s) samples
    m = (res["t"] > edges[0] + 0.15) & (res["t"] < edges[0] + 0.65)
    slope = np.polyfit(res["t"][m], res["out"][m], 1)[0]
    assert slope == pytest.approx(-ibias / C9, rel=0.05)
