"""Extract the resonator's SPICE reference curves for the web overlay.

Reads analysis/reference.json (generated by analysis/ac_analysis.py, which
stores the full wet-output response for the yellow variant at each Rldr grid
point) and writes web/resonator/spice-curves.json, decimated for the page.
Rerun after regenerating the reference:

    uv run python analysis/ac_analysis.py
    uv run python web/tools/extract-spice-curves.py
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DECIMATE = 2

ref = json.loads(
    REPO.joinpath("analysis/reference.json")
    .read_text()
    .replace("NaN", "null")  # python json.dump writes bare NaN
)

yellow = ref["colors"]["yellow"]
rldrs = sorted(float(k) for k in yellow)
freq = None
curves = {}
for r in rldrs:
    resp = yellow[f"{r:g}"]["response"]
    if freq is None:
        freq = resp["freq"][::DECIMATE]
    curves[str(int(r))] = [round(db, 2) for db in resp["out_db"][::DECIMATE]]

out = REPO / "web" / "resonator" / "spice-curves.json"
out.write_text(
    json.dumps(
        {
            "meta": "KLM-62 yellow variant wet output, ngspice AC, octave stagger",
            "rldrs": [int(r) for r in rldrs],
            "freq": [round(f, 2) for f in freq],
            "curves": curves,
        }
    )
)
print(f"wrote {out} ({out.stat().st_size // 1024} KB, {len(freq)} points x {len(curves)} curves)")
